version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Assuming your app runs on port 3000, adjust if necessary
    environment:
      - NODE_ENV=production
      - POSTGRES_URI=postgresql://postgres:password@db:5432/myappdb # Adjust as needed
    depends_on:
      - db

  db:
    image: postgres:13 # You can use any version of Postgres that suits your requirements
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: myappdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432" # Optional: only needed if you want to access the DB from outside

volumes:
  postgres_data:
