version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev  # Ensure this file exists and is configured for development
    volumes:
      - .:/app  # Match the WORKDIR in Dockerfile.dev
      - /app/node_modules  # Exclude node_modules from the volume to use the container's version
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - POSTGRES_URI=postgresql://postgres:password@db:5432/myappdb
    depends_on:
      - db
  
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: myappdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

volumes:
  postgres_data:
